# Generated by Django 5.0 on 2024-01-04 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('email', models.EmailField(max_length=120)),
                ('password', models.CharField(max_length=155, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=8)),
                ('age', models.PositiveIntegerField(null=True)),
                ('birthday', models.DateField(null=True)),
                ('student_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Student Number')),
                ('year_level', models.PositiveIntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1, verbose_name='Year Level')),
                ('semester', models.PositiveIntegerField(choices=[(1, '1st Semester'), (2, '2nd Semester')], default=1)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.course')),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
