# Generated by Django 5.0 on 2024-01-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
