# Generated by Django 5.0 on 2024-01-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(to='base.subject'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
