# Generated by Django 5.0 on 2024-01-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_student_enrolled_subjects_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
