# Generated by Django 5.0 on 2024-01-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payments',
            field=models.ManyToManyField(to='base.payfees'),
        ),
    ]
