# Generated by Django 5.0 on 2024-01-16 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_student_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payments',
        ),
        migrations.AddField(
            model_name='student',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.payfees'),
        ),
    ]
