# Generated by Django 5.0 on 2024-01-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_student_payments_student_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payments',
        ),
        migrations.AddField(
            model_name='student',
            name='payments',
            field=models.ManyToManyField(to='base.payfees'),
        ),
    ]
