# Generated by Django 5.0 on 2024-01-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_subjectenrollment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectenrollment',
            name='feedback',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
