# Generated by Django 5.0 on 2024-01-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_subjectenrollment_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, to='base.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payments',
            field=models.ManyToManyField(blank=True, to='base.payfees'),
        ),
    ]
