# Generated by Django 5.0 on 2024-01-16 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_student_enrolled_subjects_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='status',
        ),
    ]
