# Generated by Django 5.0 on 2024-01-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_subject_grade_remove_subject_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectenrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='active', max_length=30),
        ),
    ]
