# Generated by Django 5.0 on 2024-01-17 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_subject_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payfees',
            name='status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='payments',
        ),
        migrations.AlterField(
            model_name='subjectenrollment',
            name='feedback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Not Paid')], default='unpaid', max_length=15)),
                ('pay_fee', models.ManyToManyField(to='base.payfees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
    ]
