# Generated by Django 5.0 on 2024-01-17 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_payfees_status_remove_student_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='pay_fee',
        ),
        migrations.AddField(
            model_name='payments',
            name='pay_fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.payfees'),
        ),
    ]
