# Generated by Django 5.0 on 2024-01-17 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_payments_pay_fee_payments_pay_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.student'),
        ),
    ]
