# Generated by Django 5.0 on 2024-01-17 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_payments_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfees',
            name='eligable_courses',
            field=models.ManyToManyField(to='base.course'),
        ),
    ]
