# Generated by Django 5.0 on 2024-01-17 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_payfees_eligable_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='pay_fees',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
    ]
