# Generated by Django 5.0 on 2024-01-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_course_pay_fees_remove_course_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payfees',
            name='date_assigned',
        ),
        migrations.AddField(
            model_name='payments',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
